#!/usr/bin/env bash
# Bash script that will display information about subdomains
domain () {
if [ "$2" ];
then
    echo -n "The subdomain $2 is a"
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{print " " $4 " record and points to " $5}' | tail -n 1
else
    for i in www 58302-lb-01 58302-web-01 58302-web-02
    do
        echo -n "The subdomain $i is a"
        dig "$i.$1" | grep -A1 'ANSWER SECTION:' | awk '{print " " $4 " record and points to " $5}' | tail -n 1
    done
fi
}
domain "$1" "$2"
